export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Signup } from './Signup';
export { default as Cart } from './Cart';
export { default as News } from './News';
export { default as Products } from './Products';
export { default as Product } from './Product';
export { default as Search } from './Search';
export { default as Profile } from './Profile';